namespace libMBIN.NMS.Toolkit
{
    [NMS(GUID = 0xEB6D9FD81FD3E65, NameHash = 0x199FE2B)]
    public class TkMaterialFlags : NMSTemplate
    {
        // size: 0x40
        public enum MaterialFlagEnum : uint {
            _F01_DIFFUSEMAP,
            _F02_SKINNED,
            _F03_NORMALMAP,
            _F04_FEATURESMAP,
            _F05_DEPTH_EFFECT,
            _F06,
            _F07_UNLIT,
            _F08,
            _F09,
            _F10,
            _F11,
            _F12,
            _F13_UV_EFFECT,
            _F14,
            _F15_WIND,
            _F16_DIFFUSE2MAP,
            _F17,
            _F18,
            _F19_BILLBOARD,
            _F20_PARALLAX,
            _F21_VERTEXCUSTOM,
            _F22_OCCLUSION_MAP,
            _F23,
            _F24,
            _F25_MASKS_MAP,
            _F26_MASKSEXT_MAP,
            _F27,
            _F28,
            _F29,
            _F30_REFRACTION,
            _F31_DISPLACEMENT,
            _F32_REFRACTION_MASK,
            _F33_SHELLS,
            _F34,
            _F35,
            _F36_DOUBLESIDED,
            _F37_EXPLICIT_MOTION_VECTORS,
            _F38,
            _F39,
            _F40,
            _F41,
            _F42_DETAIL_NORMAL,
            _F43,
            _F44,
            _F45,
            _F46,
            _F47,
            _F48,
            _F49,
            _F50,
            _F51,
            _F52,
            _F53_COLOURISABLE,
            _F54,
            _F55_MULTITEXTURE,
            _F56_MATCH_GROUND,
            _F57,
            _F58_USE_CENTRAL_NORMAL,
            _F59,
            _F60,
            _F61,
            _F62,
            _F63,
            _F64_RESERVED_FLAG_FOR_EARLY_Z_PATCHING_DO_NOT_USE,
        }
        [NMS(Index = 0)]
        /* 0x0 */ public MaterialFlagEnum MaterialFlag;
    }
}
