namespace libMBIN.NMS.Toolkit
{
    [NMS(GUID = 0xBBAB977BB39D1A9D, NameHash = 0xCF97645F)]
    public class TkMaterialFxFlags : NMSTemplate
    {
        // size: 0x40
        public enum MaterialFxFlagEnum : uint {
            _X01,
            _X02_SKINNED,
            _X03_NORMALMAP,
            _X04_CLAMPED_SIZE,
            _X05,
            _X06,
            _X07_UNLIT,
            _X08,
            _X09,
            _X10,
            _X11,
            _X12,
            _X13_UVANIMATION,
            _X14_UVSCROLL,
            _X15,
            _X16,
            _X17,
            _X18_UVTILES,
            _X19,
            _X20,
            _X21,
            _X22,
            _X23,
            _X24,
            _X25,
            _X26_IMAGE_BASED_LIGHTING,
            _X27,
            _X28,
            _X29,
            _X30_REFRACTION,
            _X31_DISPLACEMENT,
            _X32,
            _X33,
            _X34_GLOW,
            _X35,
            _X36,
            _X37,
            _X38,
            _X39,
            _X40_SUBSURFACE_MASK,
            _X41_THICKNESS_MASK,
            _X42,
            _X43,
            _X44,
            _X45,
            _X46,
            _X47,
            _X48,
            _X49,
            _X50,
            _X51,
            _X52,
            _X53_COLOURISABLE,
            _X54,
            _X55,
            _X56,
            _X57,
            _X58,
            _X59_BIASED_REACTIVITY,
            _X60,
            _X61,
            _X62,
            _X63,
            _X64_RESERVED_FLAG_FOR_EARLY_Z_PATCHING_DO_NOT_USE,
        }
        [NMS(Index = 0)]
        /* 0x0 */ public MaterialFxFlagEnum MaterialFxFlag;
    }
}
