namespace libMBIN.NMS.GameComponents
{
    [NMS(GUID = 0x8C24548B489A52D6, NameHash = 0x6F13BCF9)]
    public class GcAlienPuzzleCategory : NMSTemplate
    {
        // size: 0x3D
        public enum AlienPuzzleCategoryEnum : uint {
            Default,
            GuildTraderNone,
            GuildTraderLow,
            GuildTraderMed,
            GuildTraderHigh,
            GuildTraderBest,
            GuildWarriorNone,
            GuildWarriorLow,
            GuildWarriorMed,
            GuildWarriorHigh,
            GuildWarriorBest,
            GuildExplorerNone,
            GuildExplorerLow,
            GuildExplorerMed,
            GuildExplorerHigh,
            GuildExplorerBest,
            BiomeHot,
            BiomeCold,
            BiomeLush,
            BiomeDusty,
            BiomeTox,
            BiomeRad,
            BiomeWeird,
            LocationSpaceStation,
            LocationShop,
            LocationOutpost,
            LocationObservatory,
            Walking,
            ExtremeWeather,
            ExtremeSentinels,
            WaterPlanet,
            FreighterCrew,
            FreighterCrewOwned,
            ShipShop,
            SuitShop,
            WeapShop,
            VehicleShop,
            MoodVeryPositive,
            MoodPositive,
            MoodNeutral,
            MoodNegative,
            MoodVeryNegative,
            Proc,
            FirstAbandonedFreighter,
            CompletedAbandonedFreighter,
            StandardAbandonedFreighter,
            BiomeSwamp,
            BiomeLava,
            AbandonedSystem,
            InhabitedSystem,
            SettlementOwned,
            SettlementNotOwned,
            PirateStation,
            StandardPilot,
            Unlocked,
            AllUnlocked,
            NotUnlocked,
            SpiderA,
            SpiderB,
            SpiderRenewed,
            LegacyStation,
        }
        [NMS(Index = 0)]
        /* 0x0 */ public AlienPuzzleCategoryEnum AlienPuzzleCategory;
    }
}
