namespace libMBIN.NMS.GameComponents
{
    [NMS(GUID = 0x5E9EC5CBFF1AC143, NameHash = 0xB2FCF6E3)]
    public class GcBaseBuildingPartStyle : NMSTemplate
    {
        // size: 0x3F
        public enum StyleEnum : uint {
            None,
            Wood,
            Metal,
            Concrete,
            Stone,
            Timber,
            Fibreglass,
            Builders,
            BIGGS_A,
            BIGGS_B,
            BIGGS_C,
            BIGGS_D,
            BIGGS_Empty0,
            BIGGS_Toilet0,
            BIGGS_Kitchen0,
            BIGGS_Bunk0,
            BIGGS_Cargo0,
            BIGGS_Cargo1,
            BIGGS_Cargo2,
            BIGGS_Cargo3,
            BIGGS_Cargo4,
            BIGGS_Cargo5,
            BIGGS_Cargo6,
            BIGGS_Cargo7,
            BIGGS_Cargo8,
            BIGGS_Cargo9,
            BIGGS_Med0,
            BIGGS_Tech0,
            BIGGS_Tech1,
            BIGGS_Window0,
            BIGGS_Window1,
            BIGGS_Window2,
            BIGGS_Planter0,
            BIGGS_STR_A,
            BIGGS_STR_B,
            BIGGS_STR_C,
            BIGGS_STR_D,
            BIGGS_STR_E,
            BIGGS_STR_F,
            BIGGS_STR_G,
            BIGGS_STR_H,
            BIGGS_STR_I,
            BIGGS_STR_J,
            BIGGS_STR_K,
            BIGGS_STR_L,
            BIGGS_STR_M,
            BIGGS_STR_N,
            BIGGS_STR_O,
            BIGGS_STR_P,
            BIGGS_STR_Q,
            BIGGS_STR_R,
            BIGGS_STR_S,
            BIGGS_STR_T,
            BIGGS_STR_U,
            BIGGS_STR_V,
            BIGGS_STR_W,
            BIGGS_STR_X,
            BIGGS_STR_Y,
            BIGGS_STR_Z,
            BIGGS_STR_AA,
            BIGGS_STR_AB,
            FRE_A,
            FRE_B,
        }
        [NMS(Index = 0)]
        /* 0x0 */ public StyleEnum Style;
    }
}
