using libMBIN.NMS.GameComponents;

namespace libMBIN.NMS.GameComponents
{
    [NMS(GUID = 0xE68D87E1532DEDB8, NameHash = 0xA688E4255C8FED76)]
    public class GcDifficultyConfig : NMSTemplate
    {
        [NMS(Size = 0x1C, EnumType = typeof(GcDifficultySettingEnum.DifficultySettingEnum))]
        /* 0x0000 */ public GcDifficultySettingCommonData[] CommonSettingsData;
        /* 0x0FC0 */ public GcDifficultyStartWithAllItemsKnownOptionData StartWithAllItemsKnownDisabledData;
        /* 0x12D0 */ public GcDifficultyStartWithAllItemsKnownOptionData StartWithAllItemsKnownEnabledData;
        [NMS(Size = 0x7, EnumType = typeof(GcDifficultyPresetType.DifficultyPresetTypeEnum))]
        /* 0x15E0 */ public NMSString0x20A[] PresetOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcDifficultyOptionGroups.DifficultyOptionGroupEnum))]
        /* 0x16C0 */ public GcDifficultyOptionUIGroup[] UILayout;
        [NMS(Size = 0x4, EnumType = typeof(GcActiveSurvivalBarsDifficultyOption.ActiveSurvivalBarsDifficultyEnum))]
        /* 0x1780 */ public NMSString0x20A[] ActiveSurvivalBarsOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcChargingRequirementsDifficultyOption.ChargingRequirementsDifficultyEnum))]
        /* 0x1800 */ public NMSString0x20A[] ChargingRequirementsOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcCurrencyCostDifficultyOption.CurrencyCostDifficultyEnum))]
        /* 0x1880 */ public NMSString0x20A[] CurrencyCostOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcDamageReceivedDifficultyOption.DamageReceivedDifficultyEnum))]
        /* 0x1900 */ public NMSString0x20A[] DamageReceivedOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcDeathConsequencesDifficultyOption.DeathConsequencesDifficultyEnum))]
        /* 0x1980 */ public NMSString0x20A[] DeathConsequencesOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcFuelUseDifficultyOption.FuelUseDifficultyEnum))]
        /* 0x1A00 */ public NMSString0x20A[] FuelUseOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x1A80 */ public NMSString0x20A[] GroundCombatOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcLaunchFuelCostDifficultyOption.LaunchFuelCostDifficultyEnum))]
        /* 0x1B00 */ public NMSString0x20A[] LaunchFuelCostOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcReputationGainDifficultyOption.ReputationGainDifficultyEnum))]
        /* 0x1B80 */ public NMSString0x20A[] ReputationGainOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcScannerRechargeDifficultyOption.ScannerRechargeDifficultyEnum))]
        /* 0x1C00 */ public NMSString0x20A[] ScannerRechargeOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x1C80 */ public NMSString0x20A[] SpaceCombatOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcBreakTechOnDamageDifficultyOption.BreakTechOnDamageProbabilityEnum))]
        /* 0x1D00 */ public NMSString0x20A[] BreakTechOnDamageOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcCreatureHostilityDifficultyOption.CreatureHostilityDifficultyEnum))]
        /* 0x1D60 */ public NMSString0x20A[] CreatureHostilityOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcDamageGivenDifficultyOption.DamageGivenDifficultyEnum))]
        /* 0x1DC0 */ public NMSString0x20A[] DamageGivenOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcEnergyDrainDifficultyOption.EnergyDrainDifficultyEnum))]
        /* 0x1E20 */ public NMSString0x20A[] EnergyDrainOptionLocIds;
        [NMS(Size = 0x4, EnumType = typeof(GcFuelUseDifficultyOption.FuelUseDifficultyEnum))]
        /* 0x1E80 */ public GcDifficultyFuelUseOptionData[] FuelUseOptionData;
        [NMS(Size = 0x3, EnumType = typeof(GcHazardDrainDifficultyOption.HazardDrainDifficultyEnum))]
        /* 0x1EE0 */ public NMSString0x20A[] HazardDrainOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcInventoryStackLimitsDifficultyOption.InventoryStackLimitsDifficultyEnum))]
        /* 0x1F40 */ public NMSString0x20A[] InventoryStackLimitsOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcItemShopAvailabilityDifficultyOption.ItemShopAvailabilityDifficultyEnum))]
        /* 0x1FA0 */ public NMSString0x20A[] ItemShopAvailabilityOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcSprintingCostDifficultyOption.SprintingCostDifficultyEnum))]
        /* 0x2000 */ public NMSString0x20A[] SprintingOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcSubstanceCollectionDifficultyOption.SubstanceCollectionDifficultyEnum))]
        /* 0x2060 */ public NMSString0x20A[] SubstanceCollectionOptionLocIds;
        [NMS(Size = 0x3, EnumType = typeof(GcItemShopAvailabilityDifficultyOption.ItemShopAvailabilityDifficultyEnum))]
        /* 0x20C0 */ public GcItemShopAvailabilityDifficultyOptionData[] ItemShopAvailabilityOptionData;
        /* 0x20F0 */ public NMSString0x20A PresetLocId;
        [NMS(Size = 0x7, EnumType = typeof(GcDifficultyPresetType.DifficultyPresetTypeEnum))]
        /* 0x2110 */ public GcDifficultySettingsData[] Presets;
        [NMS(Size = 0x3, EnumType = typeof(GcInventoryStackLimitsDifficultyOption.InventoryStackLimitsDifficultyEnum))]
        /* 0x2378 */ public GcDifficultyInventoryStackSizeOptionData[] InventoryStackLimitsOptionData;
        [NMS(Size = 0x4, EnumType = typeof(GcCurrencyCostDifficultyOption.CurrencyCostDifficultyEnum))]
        /* 0x24C8 */ public GcDifficultyCurrencyCostOptionData[] CurrencyCostOptionData;
        /* 0x2528 */ public GcDifficultySettingsData PermadeathMinSettings;
        [NMS(Size = 0x4, EnumType = typeof(GcChargingRequirementsDifficultyOption.ChargingRequirementsDifficultyEnum))]
        /* 0x2580 */ public float[] ChargingRequirementsMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcDamageReceivedDifficultyOption.DamageReceivedDifficultyEnum))]
        /* 0x2590 */ public int[] DamageReceivedAIMechTechDamageHits;
        [NMS(Size = 0x4, EnumType = typeof(GcDamageReceivedDifficultyOption.DamageReceivedDifficultyEnum))]
        /* 0x25A0 */ public float[] DamageReceivedMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x25B0 */ public float[] GroundCombatMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcLaunchFuelCostDifficultyOption.LaunchFuelCostDifficultyEnum))]
        /* 0x25C0 */ public float[] LaunchFuelCostMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcReputationGainDifficultyOption.ReputationGainDifficultyEnum))]
        /* 0x25D0 */ public float[] ReputationGainMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcScannerRechargeDifficultyOption.ScannerRechargeDifficultyEnum))]
        /* 0x25E0 */ public float[] ScannerRechargeMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x25F0 */ public float[] SentinelTimeOutMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcLaunchFuelCostDifficultyOption.LaunchFuelCostDifficultyEnum))]
        /* 0x2600 */ public float[] ShipSummoningFuelCostMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x2610 */ public float[] SpaceCombatDifficultyMultipliers;
        [NMS(Size = 0x4, EnumType = typeof(GcCombatTimerDifficultyOption.CombatTimerDifficultyOptionEnum))]
        /* 0x2620 */ public float[] SpaceCombatMultipliers;
        [NMS(Size = 0x3, EnumType = typeof(GcBreakTechOnDamageDifficultyOption.BreakTechOnDamageProbabilityEnum))]
        /* 0x2630 */ public float[] BreakTechOnDamageMultipliers;
        [NMS(Size = 0x3, EnumType = typeof(GcDamageGivenDifficultyOption.DamageGivenDifficultyEnum))]
        /* 0x263C */ public float[] DamageGivenMultipliers;
        [NMS(Size = 0x3, EnumType = typeof(GcEnergyDrainDifficultyOption.EnergyDrainDifficultyEnum))]
        /* 0x2648 */ public float[] EnergyDrainMultipliers;
        [NMS(Size = 0x3, EnumType = typeof(GcHazardDrainDifficultyOption.HazardDrainDifficultyEnum))]
        /* 0x2654 */ public float[] HazardDrainMultipliers;
        [NMS(Size = 0x3, EnumType = typeof(GcSprintingCostDifficultyOption.SprintingCostDifficultyEnum))]
        /* 0x2660 */ public float[] SprintingCostMultipliers;
        [NMS(Size = 0x3, EnumType = typeof(GcSubstanceCollectionDifficultyOption.SubstanceCollectionDifficultyEnum))]
        /* 0x266C */ public int[] SubstanceCollectionLaserAmount;
        [NMS(Size = 0x3, EnumType = typeof(GcSubstanceCollectionDifficultyOption.SubstanceCollectionDifficultyEnum))]
        /* 0x2678 */ public float[] SubstanceCollectionMultipliers;
        /* 0x2684 */ public int AllSlotsUnlockedStartingShipSlots;
        /* 0x2688 */ public int AllSlotsUnlockedStartingShipTechSlots;
        /* 0x268C */ public int AllSlotsUnlockedStartingSuitSlots;
        /* 0x2690 */ public int AllSlotsUnlockedStartingSuitTechSlots;
        /* 0x2694 */ public int AllSlotsUnlockedStartingWeaponSlots;
    }
}
