namespace libMBIN.NMS.GameComponents
{
    [NMS(GUID = 0x22A8BC986FF384B8, NameHash = 0x3849DC69)]
    public class GcExperienceDebugTriggerActionTypes : NMSTemplate
    {
        // size: 0x37
        public enum ExperienceDebugTriggerActionEnum : uint {
            None,
            Drones,
            FlyBy,
            FrigateFlyByBegin,
            FrigateFlyByEnd,
            PirateCargoAttack,
            PirateRaid,
            FreighterAttack,
            SpawnShips,
            LaunchShips,
            Mechs,
            SpaceBattle,
            PirateSpaceBattle,
            ClearPirateSpaceBattle,
            RespawnInShip,
            DebugWalker,
            DebugWalkerTitanFall,
            SpawnNexus,
            Freighters,
            NPCs,
            Sandworm,
            SpacePOI,
            BackgroundSpaceEncounter,
            Creatures,
            CameraPath,
            SummonFleet,
            SummonSquadron,
            ResetScene,
            ResetPlayerPos,
            CameraSpin,
            SpawnEnemyShips,
            PetHappy,
            PetSad,
            PetFollow,
            PetFollowClose,
            PetRest,
            PetNatural,
            PetMine,
            PetMineAndDeposit,
            RidePet,
            GhostShip,
            Normandy,
            LivingFrigate,
            UpgradeSettlement,
            SentinelFreighter,
            ClearSpacePolice,
            SpawnQuad,
            SpawnSpiderQuad,
            SpawnSpiderQuadMini,
            SpawnDockedShips,
            LaunchDockedShips,
            StartStorm,
            EndStorm,
            SpawnBugQueen,
            RemoveAllFiendsAndBugs,
        }
        [NMS(Index = 0)]
        /* 0x0 */ public ExperienceDebugTriggerActionEnum ExperienceDebugTriggerAction;
    }
}
