using libMBIN.NMS.GameComponents;
using System.Collections.Generic;

namespace libMBIN.NMS.GameComponents
{
    [NMS(GUID = 0x83A1D26BBD56747F, NameHash = 0x6C4510BB243EFA64)]
    public class GcPlayerStateData : NMSTemplate
    {
        /* 0x00000 */ public GcTerrainEditsBuffer TerrainEditData;
        [NMS(Size = 0x64)]
        /* 0x3C780 */ public GcSettlementState[] SettlementStatesV2;
        [NMS(Size = 0xC)]
        /* 0x5B540 */ public GcPlayerOwnershipData[] ShipOwnership;
        [NMS(Size = 0x7, EnumType = typeof(GcVehicleType.VehicleTypeEnum))]
        /* 0x60AC0 */ public GcPlayerOwnershipData[] VehicleOwnership;
        [NMS(Size = 0x6)]
        /* 0x63CA0 */ public GcMultitoolData[] Multitools;
        [NMS(Size = 0x5, EnumType = typeof(GcNPCHabitationType.NPCHabitationTypeEnum))]
        /* 0x65980 */ public GcNPCWorkerData[] NPCWorkers;
        [NMS(Size = 0x10)]
        /* 0x667E0 */ public Vector3f[] PlanetPositions;
        /* 0x668E0 */ public GcPlayerSpawnStateData MultiplayerSpawn;
        /* 0x669B0 */ public GcTeleportEndpoint OtherSideOfPortalReturnBase;
        /* 0x66A30 */ public GcInteractionData HoloExplorerInteraction;
        /* 0x66A50 */ public GcInteractionData HoloNooneInteraction;
        /* 0x66A70 */ public GcInteractionData HoloScepticInteraction;
        /* 0x66A90 */ public Vector4f AnomalyPositionOverride;
        /* 0x66AA0 */ public Vector4f FirstShipPosition;
        /* 0x66AB0 */ public Vector4f FirstSpawnPosition;
        /* 0x66AC0 */ public Vector3f FreighterMatrixAt;
        /* 0x66AD0 */ public Vector3f FreighterMatrixPos;
        /* 0x66AE0 */ public Vector3f FreighterMatrixUp;
        /* 0x66AF0 */ public Vector4f GraveMatrixLookAt;
        /* 0x66B00 */ public Vector4f GraveMatrixUp;
        /* 0x66B10 */ public Vector4f GravePosition;
        /* 0x66B20 */ public Vector3f NexusMatrixAt;
        /* 0x66B30 */ public Vector3f NexusMatrixPos;
        /* 0x66B40 */ public Vector3f NexusMatrixUp;
        /* 0x66B50 */ public Vector4f PortalMarkerPosition_Local;
        /* 0x66B60 */ public Vector4f PortalMarkerPosition_Offset;
        /* 0x66B70 */ public Vector4f StartGameShipPosition;
        [NMS(Size = 0x12)]
        /* 0x66B80 */ public GcPetData[] Eggs;
        [NMS(Size = 0x12)]
        /* 0x69010 */ public GcPetData[] Pets;
        [NMS(Size = 0x4)]
        /* 0x6B4A0 */ public GcSquadronPilotData[] SquadronPilots;
        [NMS(Size = 0x12)]
        /* 0x6CA20 */ public GcPetCustomisationData[] PetAccessoryCustomisation;
        [NMS(Size = 0x18, EnumType = typeof(GcCustomisationComponentData.CustomisationDataTypeEnum))]
        /* 0x6DCB0 */ public GcCharacterCustomisationSaveData[] CharacterCustomisationData;
        [NMS(Size = 0x3, EnumType = typeof(GcHotActionMenuTypes.HotActionMenuTypesEnum))]
        /* 0x6E4F0 */ public GcHotActionsSaveData[] HotActions;
        /* 0x6E8B0 */ public GcResourceElement CurrentFreighter;
        /* 0x6EB58 */ public GcResourceElement CurrentFreighterNPC;
        /* 0x6EE00 */ public GcResourceElement CurrentShip;
        [NMS(Size = 0xF, EnumType = typeof(GcWonderCreatureCategory.WonderCreatureCategoryEnum))]
        /* 0x6F0A8 */ public GcWonderRecord[] WonderCreatureRecords;
        /* 0x6F210 */ public GcInventoryContainer Chest10Inventory;
        /* 0x6F368 */ public GcInventoryContainer Chest1Inventory;
        /* 0x6F4C0 */ public GcInventoryContainer Chest2Inventory;
        /* 0x6F618 */ public GcInventoryContainer Chest3Inventory;
        /* 0x6F770 */ public GcInventoryContainer Chest4Inventory;
        /* 0x6F8C8 */ public GcInventoryContainer Chest5Inventory;
        /* 0x6FA20 */ public GcInventoryContainer Chest6Inventory;
        /* 0x6FB78 */ public GcInventoryContainer Chest7Inventory;
        /* 0x6FCD0 */ public GcInventoryContainer Chest8Inventory;
        /* 0x6FE28 */ public GcInventoryContainer Chest9Inventory;
        /* 0x6FF80 */ public GcInventoryContainer ChestMagic2Inventory;
        /* 0x700D8 */ public GcInventoryContainer ChestMagicInventory;
        /* 0x70230 */ public GcInventoryContainer CookingIngredientsInventory;
        /* 0x70388 */ public GcInventoryContainer FreighterInventory;
        /* 0x704E0 */ public GcInventoryContainer FreighterInventory_Cargo;
        /* 0x70638 */ public GcInventoryContainer FreighterInventory_TechOnly;
        /* 0x70790 */ public GcInventoryContainer GraveInventory;
        /* 0x708E8 */ public GcInventoryContainer Inventory;
        /* 0x70A40 */ public GcInventoryContainer Inventory_Cargo;
        /* 0x70B98 */ public GcInventoryContainer Inventory_TechOnly;
        /* 0x70CF0 */ public GcInventoryContainer RocketLockerInventory;
        /* 0x70E48 */ public GcInventoryContainer ShipInventory;
        /* 0x70FA0 */ public GcInventoryContainer WeaponInventory;
        [NMS(Size = 0xD, EnumType = typeof(GcWonderTreasureCategory.WonderTreasureCategoryEnum))]
        /* 0x710F8 */ public GcWonderRecord[] WonderTreasureRecords;
        [NMS(Size = 0xC, EnumType = typeof(GcWonderCustomCategory.WonderCustomCategoryEnum))]
        /* 0x71230 */ public GcWonderRecord[] WonderCustomRecords;
        [NMS(Size = 0xB, EnumType = typeof(GcInteractionBufferType.InteractionBufferTypeEnum))]
        /* 0x71350 */ public GcInteractionBuffer[] StoredInteractions;
        [NMS(Size = 0xB, EnumType = typeof(GcWonderPlanetCategory.WonderPlanetCategoryEnum))]
        /* 0x71458 */ public GcWonderRecord[] WonderPlanetRecords;
        [NMS(Size = 0xB, EnumType = typeof(GcWonderWeirdBasePartCategory.WonderWeirdBasePartCategoryEnum))]
        /* 0x71560 */ public GcWonderRecord[] WonderWeirdBasePartRecords;
        [NMS(Size = 0x10)]
        /* 0x71668 */ public GcSeed[] PlanetSeeds;
        [NMS(Size = 0x3)]
        /* 0x71768 */ public GcCharacterCustomisationData[] Outfits;
        [NMS(Size = 0x8, EnumType = typeof(GcWonderFloraCategory.WonderFloraCategoryEnum))]
        /* 0x71840 */ public GcWonderRecord[] WonderFloraRecords;
        [NMS(Size = 0x8, EnumType = typeof(GcWonderMineralCategory.WonderMineralCategoryEnum))]
        /* 0x71900 */ public GcWonderRecord[] WonderMineralRecords;
        /* 0x719C0 */ public GcExactResource CurrentWeapon;
        [NMS(Size = 0x9, EnumType = typeof(GcAlienRace.AlienRaceEnum))]
        /* 0x71A50 */ public GcStoryPageSeenDataArray[] SeenStories;
        [NMS(Size = 0x4, EnumType = typeof(GcSynchronisedBufferType.SyncBufferTypeEnum))]
        /* 0x71AE0 */ public GcSyncBufferSaveDataArray[] SyncBuffersData;
        /* 0x71CB8 */ public GcPortalSaveData VisitedPortal;
        /* 0x71B20 */ public GcInventoryLayout Chest10Layout;
        /* 0x71B38 */ public GcInventoryLayout Chest1Layout;
        /* 0x71B50 */ public GcInventoryLayout Chest2Layout;
        /* 0x71B68 */ public GcInventoryLayout Chest3Layout;
        /* 0x71B80 */ public GcInventoryLayout Chest4Layout;
        /* 0x71B98 */ public GcInventoryLayout Chest5Layout;
        /* 0x71BB0 */ public GcInventoryLayout Chest6Layout;
        /* 0x71BC8 */ public GcInventoryLayout Chest7Layout;
        /* 0x71BE0 */ public GcInventoryLayout Chest8Layout;
        /* 0x71BF8 */ public GcInventoryLayout Chest9Layout;
        /* 0x71C10 */ public GcInventoryLayout ChestMagic2Layout;
        /* 0x71C28 */ public GcInventoryLayout ChestMagicLayout;
        /* 0x71C40 */ public GcInventoryLayout CookingIngredientsLayout;
        /* 0x71C58 */ public GcInventoryLayout FreighterCargoLayout;
        /* 0x71C70 */ public GcInventoryLayout FreighterLayout;
        /* 0x71C88 */ public GcInventoryLayout RocketLockerLayout;
        /* 0x71CA0 */ public GcInventoryLayout ShipLayout;
        /* 0x71CD8 */ public GcInventoryLayout WeaponLayout;
        /* 0x71CF0 */ public NMSString0x10 BannerTitleId;
        /* 0x71D00 */ public List<GcPersistentBBObjectData> BaseBuildingObjects;
        /* 0x71D10 */ public GcSeed CurrentFreighterHomeSystemSeed;
        /* 0x71D20 */ public NMSString0x10 CurrentMissionID;
        /* 0x71D30 */ public List<ulong> ExpeditionSeedsSelectedToday;
        /* 0x71D40 */ public List<GcFleetExpeditionSaveData> FleetExpeditions;
        /* 0x71D50 */ public List<GcFleetFrigateSaveData> FleetFrigates;
        /* 0x71D60 */ public GcSeed FleetSeed;
        /* 0x71D70 */ public NMSString0x10 FreighterEngineEffect;
        /* 0x71D80 */ public List<GcGalaxyWaypoint> GalaxyWaypoints;
        /* 0x71D90 */ public List<NMSString0x20A> InteractionProgressTable;
        /* 0x71DA0 */ public NMSString0x10 JetpackEffect;
        /* 0x71DB0 */ public List<NMSString0x10> KnownProducts;
        /* 0x71DC0 */ public List<NMSString0x20A> KnownRefinerRecipes;
        /* 0x71DD0 */ public List<NMSString0x10> KnownSpecials;
        /* 0x71DE0 */ public List<NMSString0x10> KnownTech;
        /* 0x71DF0 */ public List<GcWordGroupKnowledge> KnownWordGroups;
        /* 0x71E00 */ public List<GcWordKnowledge> KnownWords;
        /* 0x71E10 */ public List<GcPortalSaveData> LastPortal;
        /* 0x71E20 */ public List<GcMaintenanceContainer> MaintenanceInteractions;
        /* 0x71E30 */ public List<GcScanEventSave> MarkerStack;
        /* 0x71E40 */ public List<GcPlayerMissionProgress> MissionProgress;
        /* 0x71E50 */ public List<GcMissionIDEpochPair> MissionRecurrences;
        /* 0x71E60 */ public List<GcScanEventSave> NewMPMarkerStack;
        /* 0x71E70 */ public List<GcPersistentBase> PersistentPlayerBases;
        /* 0x71E80 */ public List<GcMaintenanceContainer> PersonalMaintenanceInteractions;
        /* 0x71E90 */ public NMSString0x10 PreviousMissionID;
        /* 0x71EA0 */ public List<NMSString0x10> RedeemedPlatformRewards;
        /* 0x71EB0 */ public List<NMSString0x10> RedeemedSeasonRewards;
        /* 0x71EC0 */ public List<NMSString0x10> RedeemedTwitchRewards;
        /* 0x71ED0 */ public List<GcMaintenanceContainer> RefinerBufferData;
        /* 0x71EE0 */ public List<GcMaintenanceSaveKey> RefinerBufferKeys;
        /* 0x71EF0 */ public List<GcRepairTechData> RepairTechBuffer;
        /* 0x71F00 */ public List<GcSavedInteractionDialogData> SavedInteractionDialogTable;
        /* 0x71F10 */ public List<NMSString0x10> SeenBaseBuildingObjects;
        /* 0x71F20 */ public List<GcPlayerStatsGroup> Stats;
        /* 0x71F30 */ public List<Vector3f> SurveyedEventPositions;
        /* 0x71F40 */ public List<GcTelemetryStat> TelemetryStats;
        /* 0x71F50 */ public List<GcTeleportEndpoint> TeleportEndpoints;
        /* 0x71F60 */ public List<GcTradingSupplyData> TradingSupplyData;
        /* 0x71F70 */ public List<GcSavedEntitlement> UsedEntitlements;
        /* 0x71F80 */ public List<GcUniverseAddressData> VisitedAtlasStationsData;
        /* 0x71F90 */ public List<ulong> VisitedSystems;
        /* 0x71FA0 */ public List<GcInWorldUIScreenData> WristScreenData;
        /* 0x71FB0 */ public ulong ActiveSpaceBattleUA;
        /* 0x71FB8 */ public ulong CurrentMissionSeed;
        /* 0x71FC0 */ public ulong FreighterLastSpawnTime;
        /* 0x71FC8 */ public ulong HazardTimeAlive;
        /* 0x71FD0 */ public ulong LastCheckedForStatResetsTime;
        /* 0x71FD8 */ public ulong LastKnownDay;
        /* 0x71FE0 */ public ulong LastUABeforePortalWarp;
        /* 0x71FE8 */ public ulong MiniStationUA;
        /* 0x71FF0 */ public ulong MultiplayerLobbyID;
        /* 0x71FF8 */ public ulong MultiplayerPrivileges;
        /* 0x72000 */ public ulong PreviousMissionSeed;
        /* 0x72008 */ public ulong StoryPortalSeed;
        /* 0x72010 */ public ulong SunTimer;
        /* 0x72018 */ public ulong TimeAlive;
        /* 0x72020 */ public ulong TimeLastMiniStation;
        /* 0x72028 */ public ulong TimeLastSpaceBattle;
        /* 0x72030 */ public ulong TimeStamp;
        [NMS(Size = 0x8C, EnumType = typeof(GcInteractionType.InteractionTypeEnum))]
        /* 0x72038 */ public GcSavedInteractionRaceData[] SavedInteractionIndicies;
        [NMS(Size = 0xC, EnumType = typeof(GcWonderCustomCategory.WonderCustomCategoryEnum))]
        /* 0x73A78 */ public GcWonderRecordCustomData[] WonderCustomRecordsExtraData;
        [NMS(Size = 0xB)]
        /* 0x73DA8 */ public GcUniverseAddressData[] CompletedAtlasAddresses;
        [NMS(Size = 0xB)]
        /* 0x73EB0 */ public GcUniverseAddressData[] NewAtlasStationAdressData;
        [NMS(Size = 0xA)]
        /* 0x73FB8 */ public GcUniverseAddressData[] AtlasStationAdressData;
        /* 0x740A8 */ public GcDifficultyStateData DifficultyState;
        /* 0x7410C */ public GcUniverseAddressData FreighterUniverseAddress;
        /* 0x74124 */ public GcUniverseAddressData GameStartAddress1;
        /* 0x7413C */ public GcUniverseAddressData GameStartAddress2;
        /* 0x74154 */ public GcUniverseAddressData GraveUniverseAddress;
        [NMS(Size = 0x6, EnumType = typeof(GcPlayerHazardType.HazardEnum))]
        /* 0x7416C */ public float[] Hazard;
        /* 0x74184 */ public GcUniverseAddressData MultiplayerUA;
        /* 0x7419C */ public GcUniverseAddressData NexusUniverseAddress;
        /* 0x741B4 */ public GcUniverseAddressData PreviousUniverseAddress;
        /* 0x741CC */ public GcUniverseAddressData UniverseAddress;
        /* 0x741E4 */ public int ActiveMultioolIndex;
        /* 0x741E8 */ public int ActiveSpaceBattleLevel;
        /* 0x741EC */ public int BannerBackgroundColour;
        /* 0x741F0 */ public int BannerIcon;
        /* 0x741F4 */ public int BannerMainColour;
        /* 0x741F8 */ public int BoltAmmo;
        /* 0x741FC */ public int Energy;
        /* 0x74200 */ public int Health;
        /* 0x74204 */ public int HomeRealityIteration;
        /* 0x74208 */ public int KnownPortalRunes;
        /* 0x7420C */ public int LaserAmmo;
        /* 0x74210 */ public int MissionVersion;
        /* 0x74214 */ public int Nanites;
        /* 0x74218 */ public int NextSurveyedEventPositionIndex;
        /* 0x7421C */ public int PostMissionIndex;
        /* 0x74220 */ public int PrimaryPlanet;
        /* 0x74224 */ public int PrimaryShip;
        /* 0x74228 */ public int PrimaryVehicle;
        /* 0x7422C */ public int ProcTechIndex;
        /* 0x74230 */ public int ProgressionLevel;
        /* 0x74234 */ public int PulseAmmo;
        /* 0x74238 */ public int ScatterAmmo;
        /* 0x7423C */ public int SettlementStateRingBufferIndexV2;
        /* 0x74240 */ public int Shield;
        /* 0x74244 */ public int ShipHealth;
        /* 0x74248 */ public int ShipShield;
        /* 0x7424C */ public int Specials;
        /* 0x74250 */ public GcPlayerWeapons StartingPrimaryWeapon;
        /* 0x74254 */ public int StartingSeasonNumber;
        /* 0x74258 */ public GcPlayerWeapons StartingSecondaryWeapon;
        /* 0x7425C */ public int TelemetryUploadVersion;
        /* 0x74260 */ public int TradingSupplyDataIndex;
        /* 0x74264 */ public int Units;
        /* 0x74268 */ public float VRCameraOffset;
        /* 0x7426C */ public int WarpsLastMiniStation;
        /* 0x74270 */ public int WarpsLastSpaceBattle;
        /* 0x74274 */ public ushort ShopNumber;
        /* 0x74276 */ public ushort ShopTier;
        /* 0x74278 */ public NMSString0x80 SaveSummary;
        /* 0x742F8 */ public NMSString0x20 PlayerFreighterName;
        [NMS(Size = 0x12)]
        /* 0x74318 */ public bool[] UnlockedPetSlots;
        [NMS(Size = 0x10)]
        /* 0x7432A */ public bool[] GalacticMapRequests;
        [NMS(Size = 0xC)]
        /* 0x7433A */ public bool[] ShipUsesLegacyColours;
        [NMS(Size = 0x4)]
        /* 0x74346 */ public bool[] SquadronUnlockedPilotSlots;
        /* 0x7434A */ public bool BuildersKnown;
        /* 0x7434B */ public bool FirstAtlasStationDiscovered;
        /* 0x7434C */ public bool FreighterDismissed;
        /* 0x7434D */ public bool HasAccessToNexus;
        /* 0x7434E */ public bool IsNew;
        /* 0x7434F */ public bool MultiShipEnabled;
        /* 0x74350 */ public bool NextLoadSpawnsWithFreshStart;
        /* 0x74351 */ public bool OnOtherSideOfPortal;
        /* 0x74352 */ public bool RestartAllInactiveSeasonalMissions;
        /* 0x74353 */ public bool RevealBlackHoles;
        /* 0x74354 */ public bool ShipNeedsTerrainPositioning;
        /* 0x74355 */ public bool SpaceGrave;
        /* 0x74356 */ public bool SpawnGrave;
        /* 0x74357 */ public bool UseSmallerBlackholeJumps;
        /* 0x74358 */ public bool VehicleAIControlEnabled;
    }
}
