using libMBIN.NMS.GameComponents;
using System.Collections.Generic;

namespace libMBIN.NMS.GameComponents
{
    [NMS(GUID = 0x1E87AC9A0334BF13, NameHash = 0xD3C0DCB43542B48)]
    public class GcPlayerSquadronConfig : NMSTemplate
    {
        /* 0x000 */ public Vector3f CombatFormationOffset;
        /* 0x010 */ public Vector3f CombatFormationOffsetThirdPerson;
        /* 0x020 */ public Vector3f FormationOffset;
        /* 0x030 */ public Vector3f FormationOffsetThirdPerson;
        [NMS(Size = 0x4, EnumType = typeof(GcInventoryClass.InventoryClassEnum))]
        /* 0x040 */ public NMSString0x10[] PilotRankAttackDefinitions;
        /* 0x080 */ public List<NMSString0x80> RandomPilotNPCResources;
        /* 0x090 */ public List<GcAISpaceshipModelData> RandomSpaceshipResources;
        [NMS(Size = 0x4, EnumType = typeof(GcInventoryClass.InventoryClassEnum))]
        /* 0x0A0 */ public Vector2f[] PilotRankTraitRanges;
        /* 0x0C0 */ public float BreakFormationMaxForce;
        /* 0x0C4 */ public float BreakFormationMaxTurnAngle;
        /* 0x0C8 */ public float BreakFormationMinTurnAngle;
        /* 0x0CC */ public float BreakFormationTime;
        /* 0x0D0 */ public float CombatFormationOffsetCylinderHeight;
        /* 0x0D4 */ public float CombatFormationOffsetCylinderHeightThirdPerson;
        /* 0x0D8 */ public float CombatFormationOffsetCylinderLength;
        /* 0x0DC */ public float CombatFormationOffsetCylinderLengthThirdPerson;
        /* 0x0E0 */ public float CombatFormationOffsetCylinderWidth;
        /* 0x0E4 */ public float CombatFormationOffsetCylinderWidthThirdPerson;
        /* 0x0E8 */ public float FormationOffsetCylinderHeight;
        /* 0x0EC */ public float FormationOffsetCylinderHeightThirdPerson;
        /* 0x0F0 */ public float FormationOffsetCylinderLength;
        /* 0x0F4 */ public float FormationOffsetCylinderLengthThirdPerson;
        /* 0x0F8 */ public float FormationOffsetCylinderWidth;
        /* 0x0FC */ public float FormationOffsetCylinderWidthThirdPerson;
        /* 0x100 */ public float FormationOffsetRotationMaxSpeed;
        /* 0x104 */ public float FormationOffsetRotationPeriod;
        /* 0x108 */ public float FormationOffsetZOffsetVarianceMax;
        /* 0x10C */ public float FormationOffsetZOffsetVarianceMaxSpeedScale;
        /* 0x110 */ public float FormationOffsetZOffsetVarianceMin;
        /* 0x114 */ public float FormationOffsetZOffsetVarianceMinSpeedScale;
        /* 0x118 */ public float FormationOffsetZOffsetVariancePeriod;
        /* 0x11C */ public float JoinFormationArrivalTolerance;
        /* 0x120 */ public float JoinFormationBoostAlignStrength;
        /* 0x124 */ public float JoinFormationBoostMaxDist;
        /* 0x128 */ public float JoinFormationBoostMaxSpeed;
        /* 0x12C */ public float JoinFormationBoostMinDist;
        /* 0x130 */ public float JoinFormationBrakeAlignStrength;
        /* 0x134 */ public float JoinFormationBrakeDist;
        /* 0x138 */ public float JoinFormationMaxForce;
        /* 0x13C */ public float JoinFormationMaxSpeedBrake;
        /* 0x140 */ public float JoinFormationMinSpeed;
        /* 0x144 */ public float JoinFormationOffset;
        /* 0x148 */ public float LeavingForceScaleDistMax;
        /* 0x14C */ public float LeavingForceScaleDistMin;
        /* 0x150 */ public float LeavingFromPlanetOrbitMaxSpeed;
        /* 0x154 */ public float LeavingFromPlanetOrbitMinIncline;
        /* 0x158 */ public float LeavingFromPlanetOrbitWarpDist;
        /* 0x15C */ public float LeavingFromSpaceAngleFromFwdMax;
        /* 0x160 */ public float LeavingFromSpaceAngleFromFwdMin;
        /* 0x164 */ public float LeavingFromSpaceWarpDist;
        /* 0x168 */ public float LeavingMaxForceMultiplier;
        /* 0x16C */ public float MaintainFormationAlignMaxDist;
        /* 0x170 */ public float MaintainFormationAlignMaxSpeed;
        /* 0x174 */ public float MaintainFormationAlignMinDist;
        /* 0x178 */ public float MaintainFormationAlignMinSpeed;
        /* 0x17C */ public float MaintainFormationInCombatMaxTime;
        /* 0x180 */ public float MaintainFormationInCombatMinTime;
        /* 0x184 */ public float MaintainFormationLockAlignStrength;
        /* 0x188 */ public float MaintainFormationLockRollAlignStrength;
        /* 0x18C */ public float MaintainFormationLockStrength;
        /* 0x190 */ public float MaintainFormationLockStrengthBoosting;
        /* 0x194 */ public float MaintainFormationLockStrengthCombat;
        /* 0x198 */ public float MaintainFormationMaxForce;
        /* 0x19C */ public float MaintainFormationPostBoostSmoothTime;
        /* 0x1A0 */ public float MaintainFormationSharpTurnMinSpeed;
        /* 0x1A4 */ public float MaintainFormationSharpTurnMinSpeedForce;
        /* 0x1A8 */ public float MaintainFormationStartSmoothTime;
        /* 0x1AC */ public float MaintainFormationStrengthVariance;
        /* 0x1B0 */ public int MaxShipsInFormationDuringCombat;
        /* 0x1B4 */ public int MinShipsInFormationDuringCombat;
        /* 0x1B8 */ public float MinSpeedForSummonInMoveDir;
        /* 0x1BC */ public float MinTimeBetweenFormationBreaks;
        /* 0x1C0 */ public float OutOfFormationMaxTime;
        /* 0x1C4 */ public float OutOfFormationMinTime;
        /* 0x1C8 */ public float SummonArriveTime;
        /* 0x1CC */ public float SummonArriveTimeIntervalMax;
        /* 0x1D0 */ public float SummonArriveTimeIntervalMin;
        /* 0x1D4 */ public float SummonInFormationFwdOffset;
        /* 0x1D8 */ public float SummonLimitTurningTime;
        /* 0x1DC */ public float SummonPlanetDistance;
        /* 0x1E0 */ public float SummonPlanetPitchMax;
        /* 0x1E4 */ public float SummonPlanetPitchMin;
        /* 0x1E8 */ public float SummonPlanetYawMax;
        /* 0x1EC */ public float SummonPlanetYawMin;
        /* 0x1F0 */ public float SummonSpaceSpawnAngleMax;
        /* 0x1F4 */ public float SummonSpaceSpawnAngleMin;
        /* 0x1F8 */ public float SummonSpaceSpawnRangeMax;
        /* 0x1FC */ public float SummonSpaceSpawnRangeMin;
        /* 0x200 */ public float SummonStartSpeed;
        /* 0x204 */ public NMSString0x20 SquadName;
        /* 0x224 */ public bool SummonInFormation;
    }
}
