using libMBIN.NMS.Toolkit;
using libMBIN.NMS.GameComponents;

namespace libMBIN.NMS.Globals
{
    [NMS(GUID = 0xBBD84153E8A3807D, NameHash = 0x3BC94060600296E8)]
    public class GcGalaxyGlobals : NMSTemplate
    {
        [NMS(Size = 0x10, EnumType = typeof(GcGalaxyMarkerTypes.GalaxyMarkerTypeEnum))]
        /* 0x0000 */ public GcGalaxyMarkerSettings[] MarkerSettings;
        /* 0x1200 */ public GcGalaxyRenderSetupData DefaultRenderSetup;
        /* 0x1540 */ public GcGalaxyRenderSetupData FinalAnimationRenderSetup;
        /* 0x1880 */ public GcGalaxyGenerationSetupData DefaultGeneration;
        /* 0x1A00 */ public GcGalaxyGenerationSetupData FinalAnimationGeneration;
        [NMS(Size = 0x9, EnumType = typeof(GcAlienRace.AlienRaceEnum))]
        /* 0x1B80 */ public Colour[] RaceFilterDefaultColours;
        [NMS(Size = 0x9, EnumType = typeof(GcAlienRace.AlienRaceEnum))]
        /* 0x1C10 */ public Colour[] RaceFilterDeuteranopiaColours;
        [NMS(Size = 0x9, EnumType = typeof(GcAlienRace.AlienRaceEnum))]
        /* 0x1CA0 */ public Colour[] RaceFilterProtanopiaColours;
        [NMS(Size = 0x9, EnumType = typeof(GcAlienRace.AlienRaceEnum))]
        /* 0x1D30 */ public Colour[] RaceFilterTritanopiaColours;
        [NMS(Size = 0x7, EnumType = typeof(GcTradingClass.TradingClassEnum))]
        /* 0x1DC0 */ public Colour[] EconomyFilterDefaultColours;
        [NMS(Size = 0x7, EnumType = typeof(GcTradingClass.TradingClassEnum))]
        /* 0x1E30 */ public Colour[] EconomyFilterDeuteranopiaColours;
        [NMS(Size = 0x7, EnumType = typeof(GcTradingClass.TradingClassEnum))]
        /* 0x1EA0 */ public Colour[] EconomyFilterProtanopiaColours;
        [NMS(Size = 0x7, EnumType = typeof(GcTradingClass.TradingClassEnum))]
        /* 0x1F10 */ public Colour[] EconomyFilterTritanopiaColours;
        [NMS(Size = 0x7)]
        /* 0x1F80 */ public Colour[] GalacticWaypointDefaultColours;
        [NMS(Size = 0x7)]
        /* 0x1FF0 */ public Colour[] GalacticWaypointDeuteranopiaColours;
        [NMS(Size = 0x7)]
        /* 0x2060 */ public Colour[] GalacticWaypointProtanopiaColours;
        [NMS(Size = 0x7)]
        /* 0x20D0 */ public Colour[] GalacticWaypointTritanopiaColours;
        /* 0x2140 */ public GcGalaxyStarColours BaseStarDefaultColours;
        /* 0x2180 */ public GcGalaxyStarColours BaseStarDeuteranopiaColours;
        /* 0x21C0 */ public GcGalaxyStarColours BaseStarProtanopiaColours;
        /* 0x2200 */ public GcGalaxyStarColours BaseStarTritanopiaColours;
        [NMS(Size = 0x4, EnumType = typeof(GcPlayerConflictData.ConflictLevelEnum))]
        /* 0x2240 */ public Colour[] ConflictFilterDefaultColours;
        [NMS(Size = 0x4, EnumType = typeof(GcPlayerConflictData.ConflictLevelEnum))]
        /* 0x2280 */ public Colour[] ConflictFilterDeuteranopiaColours;
        [NMS(Size = 0x4, EnumType = typeof(GcPlayerConflictData.ConflictLevelEnum))]
        /* 0x22C0 */ public Colour[] ConflictFilterProtanopiaColours;
        [NMS(Size = 0x4, EnumType = typeof(GcPlayerConflictData.ConflictLevelEnum))]
        /* 0x2300 */ public Colour[] ConflictFilterTritanopiaColours;
        /* 0x2340 */ public GcGalaxyRenderAnostreakData AnostreakAway;
        /* 0x2370 */ public GcGalaxyRenderAnostreakData AnostreakFacing;
        /* 0x23A0 */ public GcInWorldUIScreenData HandMenuOffset;
        /* 0x23D0 */ public Colour HandGizmoColourAt;
        /* 0x23E0 */ public Colour HandGizmoColourInner;
        /* 0x23F0 */ public Colour HandGizmoColourRight;
        /* 0x2400 */ public Colour HandGizmoColourUp;
        /* 0x2410 */ public Vector3f HandGizmoHeadOffset;
        /* 0x2420 */ public Colour SelectionTreeColour;
        /* 0x2430 */ public GcGalaxyCameraData Camera;
        /* 0x249C */ public GcGalaxySolarSystemParams SolarSystemParameters;
        /* 0x24F4 */ public GcGalaxyAudioSetupData Audio;
        /* 0x2538 */ public Vector2f ClickToSelectIconOffset;
        /* 0x2540 */ public Vector2f GoalDistanceRange;
        /* 0x2548 */ public Vector2f SolarInfoPanelAlignment;
        /* 0x2550 */ public Vector2f SolarInfoPanelLineOffset;
        /* 0x2558 */ public Vector2f SolarInfoPanelOffset;
        /* 0x2560 */ public Vector2f SolarInfoPanelOffsetVR;
        /* 0x2568 */ public Vector2f SolarMarkerAlignmentVR;
        /* 0x2570 */ public Vector2f SolarMarkerOriginOffsetVR;
        /* 0x2578 */ public Vector2f SolarMarkerOriginOffsetVRPS4;
        /* 0x2580 */ public Vector2f SolarMarkerSizeVR;
        /* 0x2588 */ public Vector2f SolarMarkerSizeVRPS4;
        /* 0x2590 */ public float AnostreakAlpha;
        /* 0x2594 */ public float ClickToSelectIconScale;
        /* 0x2598 */ public float DistanceComputerScale;
        /* 0x259C */ public float EarlyStageMultiplier;
        /* 0x25A0 */ public float FadeGameInTime;
        /* 0x25A4 */ public float FadeGameOutTime;
        /* 0x25A8 */ public float FadeMapInTime;
        /* 0x25AC */ public float FadeMapOutTime;
        /* 0x25B0 */ public float FadeGameOutTimeCentreJourney;
        /* 0x25B4 */ public float FadeMapInTimeCentreJourney;
        /* 0x25B8 */ public float FinalFadedTime;
        /* 0x25BC */ public float FinalFadeInRate;
        /* 0x25C0 */ public float FinalFadeOutRate;
        /* 0x25C4 */ public float FinalHoldTime;
        /* 0x25C8 */ public float FinalHoldTowardsCenterTime;
        /* 0x25CC */ public float FinalTransitionAcceleration;
        /* 0x25D0 */ public float FinalTransitionInterpolationValue;
        /* 0x25D4 */ public float FinalTransitionMaxSpeed;
        /* 0x25D8 */ public float GalacticPathMaximumJumpDistanceLightyears;
        /* 0x25DC */ public float GalacticPathPreferGuideStarsTillJump;
        /* 0x25E0 */ public float HandControlDefaultOffset;
        /* 0x25E4 */ public float HandControlFreeMoveAngleOffset;
        /* 0x25E8 */ public float HandControlFreeMoveMaxOffset;
        /* 0x25EC */ public float HandControlGizmoScale;
        /* 0x25F0 */ public float HandControlMaxLockDistance;
        /* 0x25F4 */ public float HandControlMaxOffset;
        /* 0x25F8 */ public float HandControlMinLockDistance;
        /* 0x25FC */ public float HandControlMoveBlendRate;
        /* 0x2600 */ public float HandControlMoveSpeed;
        /* 0x2604 */ public float HandControlMoveSpeedTurbo;
        /* 0x2608 */ public float HandControlPitchSpeed;
        /* 0x260C */ public float HandControlPointerLength;
        /* 0x2610 */ public float HandControlPointerLengthMini;
        /* 0x2614 */ public float HandControlRotateBlendRate;
        /* 0x2618 */ public float HandControlRotateSpeed;
        /* 0x261C */ public float HandControlWarpSelectAngle;
        /* 0x2620 */ public float HandControlZoomSpeed;
        /* 0x2624 */ public float HandGizmoInnerRadius;
        /* 0x2628 */ public float HandGizmoInnerThickness;
        /* 0x262C */ public float HandGizmoLineThickness;
        /* 0x2630 */ public float HandGizmoMinAlpha;
        /* 0x2634 */ public float HandGizmoRadius;
        /* 0x2638 */ public float HandPitchFactorMin;
        /* 0x263C */ public float HandPitchFactorRange;
        /* 0x2640 */ public float HandPitchMaxDistance;
        /* 0x2644 */ public float HandTurnFactorMin;
        /* 0x2648 */ public float HandTurnFactorRange;
        /* 0x264C */ public float HandZoomFactorMin;
        /* 0x2650 */ public float HandZoomFactorRange;
        /* 0x2654 */ public float HexMarkerOuterWidth;
        /* 0x2658 */ public float HexMarkerRadius;
        /* 0x265C */ public float HexMarkerRotation;
        /* 0x2660 */ public float HexMarkerWidth;
        /* 0x2664 */ public float HexStackOffsetX;
        /* 0x2668 */ public float HexStackOffsetXOdd;
        /* 0x266C */ public float HexStackOffsetY;
        /* 0x2670 */ public float IntroCameraLookSmoothRate;
        /* 0x2674 */ public float IntroFadeInRate;
        /* 0x2678 */ public float IntroFadeOutRate;
        /* 0x267C */ public float IntroTitleFadeTrigger;
        /* 0x2680 */ public float IntroTitleHoldTime;
        /* 0x2684 */ public float IntroTitleTextureScale;
        /* 0x2688 */ public float LargeAreaColourScale;
        /* 0x268C */ public float LastSelectedPathAlphaMul;
        /* 0x2690 */ public float MarkerDropShadowMult;
        /* 0x2694 */ public float MarkerDropShadowSize;
        /* 0x2698 */ public float MenuCursorRadiusHmd;
        /* 0x269C */ public float MenuOffsetHmd;
        /* 0x26A0 */ public float MenuRotateHmd;
        /* 0x26A4 */ public float MenuScaleHmd;
        /* 0x26A8 */ public float MenuSideOffsetHmd;
        /* 0x26AC */ public float OffWorldDistance;
        /* 0x26B0 */ public float PathRenderingSelectedEndAlpha;
        /* 0x26B4 */ public float PathRenderingSelectedStartAlpha;
        /* 0x26B8 */ public float PathRenderingSelectedStepAlpha;
        /* 0x26BC */ public float PathRenderingUnselectedEndAlpha;
        /* 0x26C0 */ public float PathRenderingUnselectedStartAlpha;
        /* 0x26C4 */ public float PathRenderingUnselectedStepAlpha;
        /* 0x26C8 */ public float PathToTargetIndicatorTimeFactor;
        /* 0x26CC */ public float PathToTargetLineTimeFactor;
        /* 0x26D0 */ public float PathUIAlpha;
        /* 0x26D4 */ public float PathUIConfirmSelectionMultiplier;
        /* 0x26D8 */ public float PathUIDotLength;
        /* 0x26DC */ public float PathUIGapLength;
        /* 0x26E0 */ public float PathUIHeight;
        /* 0x26E4 */ public float PathUISelectionGenerosity;
        /* 0x26E8 */ public float PathUISelectionHandInvalidLength;
        /* 0x26EC */ public float PathUISelectionHandLineSelectAngle;
        /* 0x26F0 */ public float PathUISelectionHandSystemSelectAngle;
        /* 0x26F4 */ public float PathUISelectionMouseDeadZone;
        /* 0x26F8 */ public float PathUISelectionMouseSmoothRate;
        /* 0x26FC */ public float PathUISelectionMultiplierMouse;
        /* 0x2700 */ public float PathUISelectionMultiplierPad;
        /* 0x2704 */ public float PathUISelectionMultiplierPushing;
        /* 0x2708 */ public float PathUISlotRadiusInner;
        /* 0x270C */ public float PathUISlotRadiusOuter;
        /* 0x2710 */ public float PathUISlotRadiusRing;
        /* 0x2714 */ public float PathUISlotSpacing;
        /* 0x2718 */ public float PathUISlotWidthRing;
        /* 0x271C */ public float PathUIWidth;
        /* 0x2720 */ public float PathUIXOffset;
        /* 0x2724 */ public float PathUIYOffset;
        /* 0x2728 */ public float PlanetUIIconLargeScale;
        /* 0x272C */ public float PlanetUIIconMediumScale;
        /* 0x2730 */ public float PlanetUIIconSmallScale;
        /* 0x2734 */ public float SelectionTreeAlpha;
        /* 0x2738 */ public float ShowPopupAtCameraMinDistance;
        /* 0x273C */ public float ShowUIHelpDuration;
        /* 0x2740 */ public int SolarInfoPanelHeight;
        /* 0x2744 */ public float SolarInfoPanelScaleVR;
        /* 0x2748 */ public int SolarInfoPanelWidth;
        /* 0x274C */ public float SolarLabelScaleDistanceVR;
        /* 0x2750 */ public float SolarMarkerPanelScaleVR;
        /* 0x2754 */ public float StarBlurIntroMultiplier;
        /* 0x2758 */ public float StarBlurLineWidth;
        /* 0x275C */ public float StarBlurMaxBlurLength;
        /* 0x2760 */ public float StarBlurMaxDistanceFromCamera;
        /* 0x2764 */ public float StarBlurSizeMultiplier;
        /* 0x2768 */ public float StarPathUIWidth;
        /* 0x276C */ public float SystemInfoPanelGeneralAlpha;
        /* 0x2770 */ public float TimeForGalmapAutoNavModeSelectionInSeconds;
        /* 0x2774 */ public float TransitionTime;
        /* 0x2778 */ public NMSString0x80 MarkerDefaultHex;
        /* 0x27F8 */ public TkCurveType AnostreakAlphaCurve;
        /* 0x27F9 */ public TkCurveType AnostreakValueCurve;
        /* 0x27FA */ public bool GizmoOnHand;
        /* 0x27FB */ public TkCurveType MarkerPulseEndCurve;
        /* 0x27FC */ public TkCurveType MarkerPulseStartCurve;
        /* 0x27FD */ public bool NewStyleLookAtCamera;
        /* 0x27FE */ public TkCurveType TransitionOutCurve;
    }
}
